### ISSUE TITLE
Cross-border connection delays

### ISSUE THREAD

**Issue by hweeeeeei** [livekit/livekit-server#488]
How to solve the problem of cross-border connection delay?
Assume that user A is in Singapore, user B is in the US, user C is in China, and the LiveKit server is in Singapore.
Support SFU cascading?
Server to server?

reference:
https://webrtchacks.com/sfu-cascading/

**Comment by davidzhao** [comment]
Are you seeing actual delays that impact experience. or is this a hypothetical concern?

While SFU-SFU will *improve* the experience, it's not necessary to have smooth running, high quality sessions with sub-500ms latency. We have many users that are running global, single-homed sessions this way.

It is possible to have a multi-homed, end to end solution on top of the existing code base. (We are working on one). But due to the complexity of the stack, it'll not be available for self-hosting at this moment.

**Comment by yindaheng98** [comment]
Same demand for SFU cascading. I'm working on distributed real-time video analytics so we need to forward video between servers.
😲Would you mind providing more information about the mentioned "multi-homed, end to end solution on top of the existing code base"?

**Comment by davidzhao** [comment]
This is part of our commercial offering: https://blog.livekit.io/scaling-webrtc-with-distributed-mesh/

**Comment by yindaheng98** [comment]
😲Thanks!!!
