### ISSUE TITLE
Right configuration with port 443 busy

### ISSUE THREAD

**Issue by CSalamanca** [livekit/livekit-server#541]
Hi,
As you know, you will get a lot of new people using livekit, because with FoundryVtt server we have a module to integrate video and audio with livekit.
People are using handmade configs and they have a linux server to install both services.
It's important because on cloud we are using free tier (for example Oracle), and we cannot use a LB to have two pods, containers, or servers.
If we have all right as until now, we have FoundryVTT running on port 30000 (default port) and caddy running on 80 and 443 to redirect to 30000.
We cannot run livekit with 443 port and I am not sure if we can use it or not.

Could you please help me?

Thanks in advanced.

**Comment by bekriebel** [comment]
Creator of the Foundry module here.

Due to requirements of the browsers for using WebRTC, it must be running on port 443. However, you can configure caddy (or nginx, or any other server acting as a reverse proxy) to direct traffic based on the URL used and use two different URLs for the Foundry instance and LiveKit instance.

However, configuring this is likely beyond what the LiveKit team can offer, and I assume this ticket will be closed. I'm hoping to someday write up some guides on this kind of a setup, but I haven't had time to work on something like that yet. I'd be happy to add links to the module documentation if anyone else in the community writes up a guide.

**Comment by CSalamanca** [comment]
Ok,
I will try it, I guess with a new domain to connect with caddy, and I guess I need to redirect to "udp_port".
I missed between ports and protocols... 7780, 7781.. and I am not sure if I need redirect here (example):
turn:
  enabled: true
  udp_port: 3478
  domain: teatrodelamente.duckdns.org
or general port (typically 7780) or rtc->tcp_port (typically 7781).

Thanks.

**Comment by davidzhao** [comment]
you'd want to redirect 443 to the primary `port` (i.e. default 7880)
